# Generated by Django 5.2.14 on 2026-05-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'castes',
            },
        ),
        migrations.CreateModel(
            name='PartnerPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.PositiveSmallIntegerField(default=18)),
                ('age_max', models.PositiveSmallIntegerField(default=60)),
                ('height_min_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('height_max_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('acceptable_religions', models.JSONField(blank=True, default=list)),
                ('acceptable_castes', models.JSONField(blank=True, default=list)),
                ('preferred_education', models.CharField(blank=True, max_length=200)),
                ('preferred_profession', models.CharField(blank=True, max_length=200)),
                ('preferred_location', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'partner_preferences',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(choices=[('never_married', 'Never Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_created_by', models.CharField(choices=[('self', 'Self'), ('parent', 'Parent'), ('relative', 'Relative'), ('friend', 'Friend')], default='self', max_length=20)),
                ('mother_tongue', models.CharField(blank=True, max_length=100)),
                ('sub_caste', models.CharField(blank=True, max_length=100)),
                ('nakshatra', models.CharField(blank=True, max_length=100)),
                ('rashi', models.CharField(blank=True, max_length=100)),
                ('is_manglik', models.BooleanField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=200)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('annual_income', models.PositiveIntegerField(blank=True, null=True)),
                ('work_location', models.CharField(blank=True, max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('father_occupation', models.CharField(blank=True, max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('mother_occupation', models.CharField(blank=True, max_length=200)),
                ('brothers_count', models.PositiveSmallIntegerField(default=0)),
                ('sisters_count', models.PositiveSmallIntegerField(default=0)),
                ('family_type', models.CharField(blank=True, choices=[('joint', 'Joint'), ('nuclear', 'Nuclear')], max_length=10)),
                ('family_status', models.CharField(blank=True, max_length=200)),
                ('eating_habit', models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('vegan', 'Vegan')], max_length=10)),
                ('smoking_habit', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('occasionally', 'Occasionally')], max_length=15)),
                ('drinking_habit', models.CharField(blank=True, choices=[('no', 'No'), ('occasionally', 'Occasionally'), ('regular', 'Regular'), ('daily', 'Daily')], max_length=15)),
                ('hobbies', models.JSONField(blank=True, default=list)),
                ('bio', models.TextField(blank=True)),
                ('profile_pic_url', models.CharField(blank=True, max_length=500)),
                ('id_proof_url', models.CharField(blank=True, max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('photo_privacy', models.CharField(choices=[('public', 'Public'), ('locked', 'Locked')], default='public', max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profile_views',
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'religions',
            },
        ),
    ]
