# Generated by Django 5.2.14 on 2026-05-26 04:28

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.caste'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileview',
            name='viewed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileview',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.religion'),
        ),
        migrations.AddField(
            model_name='caste',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castes', to='profiles.religion'),
        ),
        migrations.AddIndex(
            model_name='partnerpreferences',
            index=django.contrib.postgres.indexes.GinIndex(fields=['acceptable_religions'], name='idx_gin_acceptable_religions'),
        ),
        migrations.AddIndex(
            model_name='partnerpreferences',
            index=django.contrib.postgres.indexes.GinIndex(fields=['acceptable_castes'], name='idx_gin_acceptable_castes'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['religion', 'caste', 'gender'], name='idx_religion_caste_gender'),
        ),
    ]
