# Generated by Django 5.2.14 on 2026-05-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='caste_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
