# Generated by Django 5.2.14 on 2026-05-26 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='interest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='interests.interest'),
        ),
    ]
